replicaCount: 1

image:
  repository: ghcr.io/simonlevinsky/app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

db:
  host: mysql
  port: 3306
  name: appdb
  user: appuser
  password: apppassword
  rootPassword: rootpassword